### ISSUE TITLE
Add information from Google Docs polls for BHNT#5

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlin-hack-and-tell.github.io#110]
We got all information from BHNT#5, except for one: Which one was the hack of the month?

**Comment by stefanhoth** [comment]
So I only found a summary document, probably sent out as an email. https://docs.google.com/document/d/1dH5i-rn_ktNEbnvkz3-J4uWNim3BLC8TFPDOZ-zZO44/edit?usp=sharing

It doesn't mention a winner (not sure we already did it) but I know I'm *still* telling everyone about your hack so I'd be happy to call it hack of the month: https://github.com/vog/beautify_git_hash

**Comment by vog** [comment]
Reopening, as this information still needs to be incorporated into README.md.

**Comment by vog** [comment]
Thanks, so I'm adding a tag "Unofficial hack of the month".

I remember vaguely that there was an actual voting with a winner (which wasn't me), so it would be unfair to call beautify_git_hash the actual "Hack of the month".
