### ISSUE TITLE
Transfer list of old BHNT projects / participants

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlin-hack-and-tell.github.io#2]
Transfer list of old BHNT projects / participants from BHNT forum to this page.

The forum can be found at:

https://www.meetup.com/Berlin-Hack-and-Tell/messages/boards/forum/1656561

**Comment by vog** [comment]
@stefanhoth @strathausen @ligi

I just went through the forum and collected all relevant entries for each BHNT event. (Mostly this was just the summary thread, but there were exceptions where projects were mentioned in another thread.)

I created individual tickets for each event, hoping that this will motivate more people to help out:

* #22 Add list of hacks for BHNT#2
* #23 Add list of hacks for BHNT#3
* #24 Add list of hacks for BHNT#4
* #14 Add list of hacks for BHNT#5
* #15 Add list of hacks for BHNT#9
* #37 Add list of hacks for BHNT#10
* #38 Add list of hacks for BHNT#11
* #16 Add list of hacks for BHNT#12
* #39 Add list of hacks for BHNT#13
* #40 Add list of hacks for BHNT#15
* #41 Add list of hacks for BHNT#16
* #42 Add list of hacks for BHNT#17
* #26 Add list of hacks for BHNT#18
* #27 Add list of hacks for BHNT#19
* #28 Add list of hacks for BHNT#20
* #29 Add list of hacks for BHNT#21
* #30 Add list of hacks for BHNT#22
* #17 Add list of hacks for BHNT#25
* #18 Add list of hacks for BHNT#26
* #31 Add list of hacks for BHNT#29
* #32 Add list of hacks for BHNT#30
* #33 Add list of hacks for BHNT#32
* #34 Add list of hacks for BHNT#38
* #35 Add list of hacks for BHNT#40
* #36 Add list of hacks for BHNT#44
* #19 Add list of hacks for BHNT#45
* #20 Add list of hacks for BHNT#46
* #21 Add list of hacks for BHNT#47

**Comment by ligi** [comment]
Just saw this - respect! We should really free this data from the hands of meetup - if they are gone all this might be lost !-)
