### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by ligi** [berlin-hack-and-tell/berlin-hack-and-tell.github.io#45]
We need to do some SEO magic so that when someone googles for Berlin hack and tell the meetup page is not the first one but this one.

**Comment by vog** [comment]
I agree, but what exactly do we need to do? Here are my ideas, additions are welcome:

- [ ] Add a link from https://www.meetup.com/Berlin-Hack-and-Tell/ to https://berlin-hack-and-tell.github.io/
- [ ] Replace the HTTP redirect from berlin.hackandtell.org to Meetup with a redirect to https://berlin-hack-and-tell.github.io/
Caveat: That redirect is a 301 Permanent redirect. :-( But I think it is still worth trying.

@stefanhoth Do you agree? Could you do this?

**Comment by stefanhoth** [comment]
I can tell the admins of hackandtell.org to add a CNAME for berlin.hackandtell.org (currently redirecting to the meetup group) and set up the repo to be served under that url. Any objections?

**Comment by vog** [comment]
That's even better!

Still, to convince Google entirely, I think we also need a link from Meetup back to berlin.hackandtell.org

**Comment by stefanhoth** [comment]
Agreed but only if that link doesn't lead back to the same site 😉

**Comment by ligi** [comment]
:+1:

currently there is a link from meetup to google+ - this was never really
active and perhaps we can just replace this

**Comment by vog** [comment]
Oh the irony! Replacing a Google+ link to convince Google. :grin:

**Comment by stefanhoth** [comment]
Yes, for sure we can use it and also in the "about this group" text. But only if the migration of the subdomain is done.

**Comment by vog** [comment]
Is there any progress on the berlin.hackandtell.org subdomain?

**Comment by stefanhoth** [comment]
Not yet. Still waiting for someone with DNS access to hackandtell.org. Seems a bit difficult.

**Comment by stefanhoth** [comment]
I sent an email to the person who registered the domain. Hope that will help.

**Comment by stefanhoth** [comment]
@vog @ligi We are live! berlin.hackandtell.org

**Comment by stefanhoth** [comment]
I think everything has been covered. Reopen if I missed sth.

**Comment by ligi** [comment]
YAY

**Comment by vog** [comment]
Finally!
