### ISSUE TITLE
Strange last entry for BHNT#1

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlin-hack-and-tell.github.io#49]
While cleaning up BHNT#1, I noticed that there is no presenter for the last (6th) entry:

* Memoryous - Machine learning test grading over email (Not yet live) (Project, GitHub) by ???

Moreover, I can only find 5 entries in the forum: https://www.meetup.com/Berlin-Hack-and-Tell/messages/boards/thread/12298041

@strathausen Where did you get this information from? Can you find the presenter?

@stefanhoth Do you know who presented this on BHNT#1?

**Comment by strathausen** [comment]
I got it from here:
http://grical.org/e/show/915/

which was mentioned in the meetup-thread:
https://www.meetup.com/Berlin-Hack-and-Tell/events/19514831/

**Comment by vog** [comment]
@stefanhoth Any idea who was the presenter?

**Comment by stefanhoth** [comment]
Yes, it was @Quesada who pitched his startup. We didn't have strict rules back then and were happy for people contributing. 😉
