### ISSUE TITLE
Which one was the "First seen on BHNT" project?

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlin-hack-and-tell.github.io#77]
At the last BHNT#49 event it was mentioned that there is some now-popular project which was "first seen on BHNT".

* Which one was it?
* At which BHNT event?

**Comment by ligi** [comment]
I referenced @Miserlou  s talk at #33c3  -https://media.ccc.de/v/33c3-7865-gone_in_60_milliseconds
![Uploading Selection_012.png…]()
